apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: kube-01
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pvc
  containers:
  - image: busybox:latest
    name: test-container
    command: ["sh", "-c", "echo $(date) > /data/message.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: task-pv-storagekubectl get pv
