apiVersion: v1
kind: Pod
metadata:
  name: envfrom-pod
spec:
  containers:
    - name: demo
      image: busybox
      envFrom:
        - configMapRef:
            name: app-config
      command: ["sh", "-c", "env && sleep 3600"]